export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'Bypass Doors' | 'Bifold Doors' | 'Pivot Doors' | 'Barn Doors' | 'Hardware' | 'Mirrors';
  image: string;
  specs: { label: string; value: string }[];
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Ashbury 2 Panel Bifold Door',
    description: 'Classic two-panel design with traditional styling for timeless closet solutions.',
    price: 419.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_199065_hd.jpg',
    specs: [
      { label: 'Material', value: 'Premium engineered wood core' },
      { label: 'Finish', value: 'Durable laminate surface' },
      { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
      { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
      { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '2',
    name: 'Barn Door Privacy Latch',
    description: 'Teardrop-style privacy latch for barn doors with secure locking mechanism.',
    price: 89.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199078_Barn_Door_Lock_Tear_Drop_Privacy_Latch.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '3',
    name: 'Cairns Pull Handle',
    description: 'Black rectangular door pull handle with mounting hardware for barn door applications.',
    price: 69.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199077_Handles_Pulls_Cairns.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '4',
    name: 'Continental Pavilion Barn Door',
    description: 'Modern Continental design with clean lines and contemporary styling for barn door applications.',
    price: 679.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_176733_Continental_Pavilion_5_Lite.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '5',
    name: 'Crochet Multi-X Pivot Door',
    description: 'Decorative pivot door with intricate multi-X pattern design for unique style statement.',
    price: 549.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_205721_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '6',
    name: 'Euro 1-Lite Bifold Door',
    description: 'Space-saving bifold design with single glass panel for compact closet solutions.',
    price: 389.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_155701_Bifold_Closet_Door_Euro_1_Lite_v2.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
        { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '7',
    name: 'Euro 1-Lite Bypass Door',
    description: 'Premium bypass closet door with single glass panel for modern elegance and maximum light transmission.',
    price: 459.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_155725_Bypass_Closet_Doors_Euro_1_Lite_v2.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '8',
    name: 'Euro 1-Lite Pivot Door',
    description: 'Modern pivot door with single glass panel for contemporary closet design.',
    price: 529.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_205722_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '9',
    name: 'Euro 3-Lite Bifold Door',
    description: 'Bifold door with triple glass panels combining space efficiency with elegant design.',
    price: 429.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_155731_Bifold_Closet_Door_Euro_3_Lite_v2.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
        { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '10',
    name: 'Euro 3-Lite Bypass Door',
    description: 'Elegant bypass door with triple glass panels for enhanced light transmission and contemporary styling.',
    price: 589.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_155732_Bypass_Closet_Doors_Euro_3_Lite_v2.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '11',
    name: 'Florence LED Mirror 21x31',
    description: 'Elegant oval LED-lit mirror with black frame, perfect for modern bathroom installations.',
    price: 199.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199088_Mirror_Florence_21_x_31.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '12',
    name: 'Georgian 6 Panel Bifold Door',
    description: 'Traditional Georgian styling in space-saving bifold configuration with raised panel details.',
    price: 449.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_199063_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
        { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '13',
    name: 'Georgian 6 Panel Bypass Door',
    description: 'Classic Georgian design with six raised panels for traditional elegance and timeless appeal.',
    price: 529.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_176725_Bypass_Closet_Doors_Georgian_6_Panel.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '14',
    name: 'Harmony 1-Lite Bypass Door',
    description: 'Versatile single glass panel design with clean lines for versatile home styling.',
    price: 469.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_176732_Continental_Dunmore_K_Lite.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '15',
    name: 'Heritage Gladstone Barn Door',
    description: 'Distinctive Gladstone design with angled plank pattern for unique barn door styling.',
    price: 769.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192859_Heritage_Gladstone_2_Lite_Angled_Plank_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '16',
    name: 'Heritage Glass Panel Barn Door',
    description: 'Modern barn door with glass panel insert combining rustic charm with contemporary light.',
    price: 799.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192857_Heritage_Glass_Panel_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '17',
    name: 'Heritage Herringbone Barn Door',
    description: 'Rustic barn door with authentic herringbone chevron pattern for farmhouse charm.',
    price: 749.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192861_Heritage_Herringbone_Chevron_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '18',
    name: 'Heritage Rustic Plank Barn Door',
    description: 'Authentic rustic plank design barn door for traditional farmhouse aesthetics.',
    price: 699.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192853_Heritage_Rustic_Plank_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '19',
    name: 'Heritage Salinas Z-Design Barn Door',
    description: 'Distinctive Z-pattern barn door with rustic Heritage styling for unique character.',
    price: 739.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_176737_Heritage_Salinas_Z_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '20',
    name: 'Heritage Shaker Barn Door',
    description: 'Clean Shaker-style barn door with traditional craftsmanship and modern functionality.',
    price: 729.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192856_Heritage_Shaker_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '21',
    name: 'Heritage Sierra K-Design Barn Door',
    description: 'Rustic Sierra barn door with distinctive K-pattern design for authentic farmhouse appeal.',
    price: 719.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_205717_Heritage_Sierra_K_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '22',
    name: 'Melody LED Mirror 32x24',
    description: 'Rectangular LED-lit mirror for contemporary bathroom design with integrated lighting.',
    price: 249.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199089_Mirror_Melody_32_x_24.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '23',
    name: 'Parsons Flush Panel Bifold Door',
    description: 'Minimalist flush panel bifold door perfect for contemporary and modern interiors.',
    price: 399.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
        { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '24',
    name: 'Parsons Flush Panel Bypass Door',
    description: 'Clean, minimalist flush panel design perfect for modern and contemporary interiors.',
    price: 489.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_176728_Bypass_Closet_Doors_Parsons_Flush_Panel.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '25',
    name: 'Provincial 8-Lite Pivot Door',
    description: 'Elegant pivot door with eight glass panels for sophisticated closet entrance solutions.',
    price: 599.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_205720_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '26',
    name: 'Rectangle Flush Pull Handle',
    description: 'Black rectangular flush-mount door pull with recessed design for contemporary styling.',
    price: 59.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199079_Handles_Pulls_Rectangle_Flush.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '27',
    name: 'Round Flush Pull Handle',
    description: 'Stainless steel round flush-mount door pull with brushed finish for modern aesthetics.',
    price: 49.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199074_Handles_Pulls_Round_Flush.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '28',
    name: 'Spectrum Bypass Bracket Kit',
    description: 'Professional bypass barn door bracket system for dual door installations.',
    price: 349.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199072_Accessories_Spectrum_Bypass_Barn_Door_Bracket_Kit.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '29',
    name: 'Spectrum Soft Close Kit',
    description: 'Advanced soft-close mechanism for smooth, quiet barn door operation with premium feel.',
    price: 159.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199084_Accessories_Easy_Clip_153_Soft_Close.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '30',
    name: 'Spectrum Track Hardware Kit',
    description: 'Premium barn door track hardware system with smooth operation and durable construction.',
    price: 299.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199080_Replacement_Part_Spectrum_Track.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '31',
    name: 'Symphony LED Mirror 32x24',
    description: 'Premium rectangular LED-lit mirror with modern styling for luxury bathroom applications.',
    price: 279.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199093_Mirror_Symphony_32_x_24.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
];
