export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'Bypass Doors' | 'Bifold Doors' | 'Pivot Doors' | 'Barn Doors' | 'Hardware' | 'Mirrors';
  image: string;
  specs: { label: string; value: string }[];
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Ashbury 2 Panel Design Steel Frame Bypass Door',
    description: 'The Ashbury bypass door\'s raised 2-panel square top design offers universal appeal and reliable operation. The closet door\'s prefinished, flush, hardboard inserts are encased in a Bright White narrow steel frame with an integrated ergonomic handle.',
    price: 299.00,
    category: 'Bypass Doors',
    image: 'https://www.renin.com/wp-content/uploads/2021/01/BY0108_Ashbury-Bypass-Door_Lifestyle-Open-1365x2048.jpg',
    specs: [
      { label: 'Frame Finish', value: 'Bright White' },
      { label: 'Insert Type', value: 'White Pre-finished 2 Panel Board' },
      { label: 'Dimensions', value: 'Width 47-48", Height 80-81"' },
      { label: 'Hardware', value: 'Easy-Hang sliding system with integrated ergonomic handle' },
      { label: 'Track System', value: 'Low-profile Invisi-Track system' },
      { label: 'Connector', value: 'Quick-Click Anti-Jump Connector with bottom guide' },
      { label: 'Adjustability', value: 'Corrects out-of-square openings (+/- 1/4-inch)' },
      { label: 'Installation', value: 'Preassembled and ready for fast installation' },
      { label: 'Custom Sizes', value: 'Not available due to embossed panel design' },
      { label: 'Back Side', value: 'Not painted' },
    ],
  },
  {
    id: '2',
    name: 'Tear Drop Latch',
    description: 'Our Tear Drop Privacy Latch barn door lock with mounting hardware is designed to provide privacy within any room including bedroom, bathroom or office. This easy installation works on most barn doors. To lock, simply slide the latch towards the strike plate.',
    price: 72.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199065_hd.jpg',
    specs: [
        { label: 'Installation', value: 'Easily installs to create privacy within a room' },
        { label: 'Finishes', value: 'Available in Matte Black and Satin Nickel' },
        { label: 'Compatibility', value: 'Works on most barn doors' },
        { label: 'Installation Note', value: 'Not recommended for barn door kits with wood blocking above the door' },
        { label: 'Operation', value: 'Slide latch towards strike plate to lock' },
    ],
  },
  {
    id: '3',
    name: 'Cairns Door Handle',
    description: 'Single door handle (6 1/2″ x 1″ x 1 1/2″) with mounting screws.',
    price: 38.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199065_hd.jpg',
    specs: [
        { label: 'Dimensions', value: '6 1/2″ x 1″ x 1 1/2″' },
        { label: 'Installation', value: 'Designed to install to external side of Barn Door' },
        { label: 'Included Hardware', value: 'Mounting screws included' },
    ],
  },
  {
    id: '4',
    name: 'Pavilion 5-Lite Barn Door Kit',
    description: 'Serving as a focal statement for any room design, our 5-Lite Pavilion Barn Door is certain to impress with its geometric, modern style. The ladder-like, horizontal, 5-Lite tempered frosted glass inserts on this modern barn door are elegantly outlined in solid engineered wood. These pre-finished sliding barn doors require no priming, painting or staining, and offer years of dependable use and a lasting impression.',
    price: 639.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_176733_Continental_Pavilion_5_Lite.jpg',
    specs: [
        { label: 'Design', value: '5-Lite tempered frosted glass inserts with geometric modern style' },
        { label: 'Material', value: 'Solid engineered wood with tempered frosted glass' },
        { label: 'Finish', value: 'Pre-finished Bright White or Iron Age - no priming/painting required' },
        { label: 'Hardware', value: 'Hardened steel bent strap hardware in Rustic Matte Black' },
        { label: 'Installation', value: 'Quick Hang hardware with pre-drilled mounting holes' },
        { label: 'Track System', value: 'Traditional barn door track with concealed floor guide' },
        { label: 'Floor Guide', value: 'Optional adjustable wall mounted guide' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '5',
    name: 'Crochet Multi-X Design Pivot Door',
    description: 'Looking for a unique closet door idea? The Crochet multi-X design pivot closet door\'s handsome design interweaves stacked X\'s against a translucent background. Blending Old World charm and new design styling, the door\'s engineered wood frame is prefinished with a scratch-resistant, smooth Graphite Gray wood grain finish overlaying a contemporary frosted glass insert. A round closet door knob pull in Satin Nickel finish operates the spring-loaded pivot connectors, allowing your doors to swing open for maximum access to your space.',
    price: 459.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_205721_hd.jpg',
    specs: [
        { label: 'Frame Finish', value: 'Graphite Gray wood grain' },
        { label: 'Insert Type', value: 'Tempered frosted glass' },
        { label: 'Dimensions', value: 'Width 47-48", Height 80 1/4-80 5/8"' },
        { label: 'Hardware', value: 'Spring-loaded pivot connectors with magnetic catch' },
        { label: 'Handle', value: 'Round closet door knob pull in Satin Nickel finish' },
        { label: 'Material', value: 'Solid engineered wood frame' },
        { label: 'Maintenance', value: 'Scratch-resistant, will not warp or crack from humidity' },
        { label: 'Customization', value: 'Cannot be painted, stained or cut' },
    ],
  },
  {
    id: '6',
    name: 'Euro 1-Lite Bifold Door',
    description: 'The stylish sophistication of our Euro 1-lite sliding bifold closet doors with contemporary frosted glass inserts can clearly be attributed to their Italian design heritage. Each of the doors two panels feature full-height frosted glass inserts and solid engineered wood framing prefinished in Off-White and completed with a round knob pull in Satin Nickel finish. Bifold closet doors fold into each other to provide you up to 95% access to your closet with minimal floor clearance and without taking up space within your room. Incorporating a trackless floor design, these folding closet doors\' Free-Glide top roll system makes them the smoothest and easiest opening and closing action we offer in a bifold door.',
    price: 409.00,
    category: 'Bifold Doors',
    image: 'https://www.renin.com/wp-content/uploads/2020/11/EU3010_Euro_1-Lite-Bifold_Off-White_Lifestyle-1-1368x1536.jpg',
    specs: [
        { label: 'Frame Finish', value: 'Off-White' },
        { label: 'Insert Type', value: 'Tempered frosted glass' },
        { label: 'Dimensions', value: 'Width 24", Height 80 1/4-80 5/8"' },
        { label: 'Design', value: 'Two panels with full-height frosted glass inserts' },
        { label: 'Hardware', value: 'Sliding mini 3-wheel connector, trackless floor design' },
        { label: 'Handle', value: 'Round closet door knob pull in Satin Nickel finish' },
        { label: 'Access', value: 'Up to 95% closet access' },
        { label: 'Material', value: 'Solid engineered wood framing' },
        { label: 'Maintenance', value: 'Scratch-resistant, will not warp or crack from humidity' },
        { label: 'Customization', value: 'Cannot be painted, stained or cut' },
    ],
  },
  {
    id: '7',
    name: 'Euro 1-Lite Bypass Door',
    description: 'This European-inspired 1-lite sliding bypass closet door system with frosted glass insert conceals storage and preserves privacy, while adding a feeling of openness and light to your room. A smooth, Off-White painted-look frame surrounds the glass for a neat, modern appearance that pairs well with mid-century modern, minimalistic, industrial and urban home designs. Ideal for closets large or small, the sliding closet doors can be ordered with two or four panels.',
    price: 519.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_155725_Bypass_Closet_Doors_Euro_1_Lite_v2.jpg',
    specs: [
        { label: 'Frame Finish', value: 'Off-White painted look' },
        { label: 'Insert Type', value: 'Tempered frosted glass' },
        { label: 'Dimensions', value: 'Width 47-48", Height 80 1/4-80 7/8"' },
        { label: 'Design', value: 'European-inspired with frosted glass insert' },
        { label: 'Hardware', value: 'Tool-free, dial-adjust roller closet door hardware' },
        { label: 'Track System', value: 'Trackless closet door design' },
        { label: 'Material', value: 'Solid engineered wood frames' },
        { label: 'Maintenance', value: 'Scratch-resistant, will not warp or crack from humidity' },
        { label: 'Customization', value: 'Cannot be painted, stained or cut; custom sizes not available' },
        { label: 'Configuration', value: 'Available with two or four panels' },
    ],
  },
  {
    id: '8',
    name: 'Euro 1-Lite Design Pivot Door',
    description: 'This European-inspired and Italian-designed, 1-lite pivot closet door with frosted glass insert highlights stylish heritage and elegance. The full-length glass insert adds a feeling of openness and light to your room, while concealing storage and preserving privacy. The hinge free design of this modern closet door allows for more versatility in adjusting the door for out of square openings. These doors allow full access without taking up the floor space of a traditional swing door. The glass insert is framed in a prefinished, scratch-resistant, smooth Off-White solid engineered wood with matching fascia, saving you time and mess by skipping the painting and clean-up of unfinished doors.',
    price: 529.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Frame Finish', value: 'Off-White' },
        { label: 'Insert Type', value: 'Tempered frosted glass' },
        { label: 'Dimensions', value: 'Width 23-24", Height 80 1/4-80 5/8"' },
        { label: 'Design', value: 'European-inspired and Italian-designed' },
        { label: 'Hardware', value: 'Spring-loaded pivot connectors with magnetic catch' },
        { label: 'Handle', value: 'Round closet door knob pull in Satin Nickel finish' },
        { label: 'Material', value: 'Solid engineered wood frames' },
        { label: 'Maintenance', value: 'Scratch-resistant, will not warp or crack from humidity' },
        { label: 'Customization', value: 'Cannot be painted, stained or cut' },
        { label: 'Installation', value: 'Hinge-free design for out-of-square openings' },
    ],
  },
  {
    id: '9',
    name: 'Euro 3-Lite Design Pivot Door',
    description: 'This European-inspired and Italian-designed, 3-lite pivot closet door with frosted glass insert highlights stylish heritage and elegance. The 3 frost glass inserts add a feeling of openness and light to your room, while concealing storage and preserving privacy. The hinge free design allows for more versatility in adjusting the door for out of square openings. Looking for a closet door idea to replace a traditional swing door, these doors allow full access without taking up the floor space of a swing door. Solid engineered wood framing features a scratch-resistant, smooth Off-White finish, framing three vertically stacked, translucent glass windows.',
    price: 429.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Width', value: '23 - 24"' },
        { label: 'Height', value: '80 1/4 - 80 5/8"' },
        { label: 'Frame Finish', value: 'Off-White' },
        { label: 'Insert Type', value: 'Tempered Frosted Glass' },
    ],
  },
  {
    id: '10',
    name: 'Euro 3-Lite Bifold Door',
    description: 'Our Euro 3-lite sliding bifold closet doors showcase a stack window design with contemporary frosted glass inserts that protect privacy while adding light. Each of the bifold doors two panels feature three vertical, frosted glass inserts. Our Free-Glide top roll system makes this the smoothest and easiest opening and closing action we offer in a bifold door. Bifold closet doors fold into each other to provide you up to 95% access to your closet with minimal floor clearance and without taking up space within your room. Their solid engineered wood framing is prefinished in Off-White and completed with a round closet door knob pull in Satin Nickel finish.',
    price: 409.00,
    category: 'Bifold Doors',
    image: 'https://www.renin.com/wp-content/uploads/2020/12/EU3080_Euro-3-Lite-Bifold_Off-White_Lifestyle-2-1536x1536.jpg',
    specs: [
        { label: 'Frame Finish', value: 'Off-White' },
        { label: 'Insert Type', value: 'Tempered frosted glass' },
        { label: 'Dimensions', value: 'Width 24", Height 80 1/4-80 5/8"' },
        { label: 'Design', value: 'Two panels with three vertical frosted glass inserts each' },
        { label: 'Hardware', value: 'Sliding mini 3-wheel connector, trackless floor design' },
        { label: 'Handle', value: 'Round closet door knob pull in Satin Nickel finish' },
        { label: 'Access', value: 'Up to 95% closet access' },
        { label: 'Material', value: 'Solid engineered wood framing' },
        { label: 'Maintenance', value: 'Scratch-resistant, will not warp or crack from humidity' },
        { label: 'Customization', value: 'Cannot be painted, stained or cut' },
    ],
  },
  {
    id: '11',
    name: 'Euro 3-Lite Bypass Door',
    description: 'Our European-inspired, 3-lite sliding bypass closet door system showcases frosted glass for translucent light transmission and privacy. A clean, bright, contemporary appearance makes them ideal for mid-century modern, minimalistic, industrial and urban home designs. The sliding closet doors are constructed with engineered wood framing with a smooth, Off-White finish on both the front and back.',
    price: 519.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_155732_Bypass_Closet_Doors_Euro_3_Lite_v2.jpg',
    specs: [
        { label: 'Width', value: '47 - 48"' },
        { label: 'Height', value: '80 1/4 - 80 7/8"' },
        { label: 'Frame Finish', value: 'Off-White' },
        { label: 'Insert Type', value: 'Tempered Frosted Glass' },
    ],
  },
  {
    id: '12',
    name: 'Euro 5-Lite Bypass Door',
    description: 'Featuring five frosted glass inserts and Iron Age finished framing, these Italian-designed 5-lite sliding bypass closet doors add light and openness to any room without sacrificing privacy. The sliding closet doors are constructed of solid engineered wood with a smooth wood grain look. Whether you install them on a closet, in a hallway or between rooms, these doors can scale to the task with two panels for smaller openings or four panels for more expansive ones.',
    price: 519.00,
    category: 'Bypass Doors',
    image: 'https://www.renin.com/wp-content/uploads/2020/11/EU2470_Euro-5-Lite-Bypass_Iron-Age_Lifestyle-1365x2048.jpg',
    specs: [
        { label: 'Width', value: '47 - 48"' },
        { label: 'Height', value: '80 1/4 - 80 7/8"' },
        { label: 'Frame Finish', value: 'Iron Age' },
        { label: 'Insert Type', value: 'Tempered Frosted Glass' },
    ],
  },
  {
    id: '12',
    name: 'Florence 24" x 32" Oval Backlit Mirror',
    description: 'The Florence Backlit Oval Mirror enhances the elegance of any room in your home and hangs vertically to showcase the most flattering reflection. Highlighting the mirror\'s distinctive, elliptical shape, its inset LED lighting turns on, off or dims with a simple touch-sensor control to provide even, balanced 360-degree lighting perfect for tasks requiring full face illumination. LED lights use 75% less energy compared to incandescent lighting making them more efficient, versatile and long lasting.',
    price: 199.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Dimensions', value: '24" x 32"' },
        { label: 'Shape', value: 'Oval' },
        { label: 'Lighting', value: 'Inset LED with touch-sensor control' },
        { label: 'Features', value: '360-degree balanced lighting, dimmable' },
        { label: 'Energy Efficiency', value: '75% less energy than incandescent' },
        { label: 'Mounting', value: 'Hangs vertically' },
        { label: 'Certification', value: 'UL/CE Certified' },
    ],
  },
  {
    id: '13',
    name: 'Georgian 6 Panel Bifold Door',
    description: 'Adding a traditional accent to any room, the Georgian bifold closet door features a raised 6-panel square top design, prefinished in white wood grain texture and encased in a Bright White narrow steel frame. An attached metal pull operates the door\'s rolling pivot system to reveal an additional 4 inches for more complete access to your closet or space. Spanning openings with two panels or four, the steel bifold doors\' Easy-Roll bifold closet door hardware offers smooth travel and the low-profile bottom track makes for quick installation and easy cleaning.',
    price: 289.00,
    category: 'Bifold Doors',
    image: 'https://www.renin.com/wp-content/uploads/2020/11/BI0221_16_Georgian_Wood-Grain-Textured_Single_Closed_Lifestyle-1465x2048.jpg',
    specs: [
        { label: 'Width', value: '23 3/4 - 24"' },
        { label: 'Height', value: '80 3/8 - 80 7/8"' },
        { label: 'Frame Finish', value: 'Bright White' },
        { label: 'Insert Type', value: 'White Pre-finished 6 Panel Board' },
    ],
  },
  {
    id: '14',
    name: 'Georgian 6 Panel Bypass Door',
    description: 'The Georgian bypass closet door displays a raised 6-panel design, prefinished in white wood grain texture. The door\'s design features two columns of panel inserts with a square top panel set above two vertical rectangular panels. The flush, hardboard inserts are encased in a Bright White narrow steel frame with an integrated ergonomic handle.',
    price: 299.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Width', value: '47 - 48"' },
        { label: 'Height', value: '80 - 81"' },
        { label: 'Frame Finish', value: 'Bright White' },
        { label: 'Insert Type', value: 'White Pre-finished 6 Panel Board' },
    ],
  },
  {
    id: '15',
    name: 'Harmony 1-Lite Bypass Door',
    description: 'The Harmony sliding closet door features full-length mirrors with narrow framing to create a winning combination for both traditional and modern design. The high-quality engineered wood framing is prefinished in Bright White to match any interior decorating palette. The bypass door panels\' mirror inserts enhance the functionality of your space, while seeming to enlarge your room with extra depth, dimension and reflection.',
    price: 489.00,
    category: 'Bypass Doors',
    image: 'https://www.renin.com/wp-content/uploads/2020/11/EU3210-Harmony-Closet-Doors-White-Mirror-Bypass_Beauty-1-1313x1536.jpg',
    specs: [
        { label: 'Width', value: '47 - 48"' },
        { label: 'Height', value: '80 1/4 - 80 7/8"' },
        { label: 'Frame Finish', value: 'Bright White' },
        { label: 'Insert Type', value: 'Mirror' },
    ],
  },
  {
    id: '16',
    name: 'Heritage Gladstone Barn Door',
    description: 'Distinctive Gladstone design with angled plank pattern for unique barn door styling.',
    price: 769.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '17',
    name: 'Heritage Glass Panel Barn Door',
    description: 'Modern barn door with glass panel insert combining rustic charm with contemporary light.',
    price: 799.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '18',
    name: 'Heritage Herringbone Barn Door',
    description: 'Rustic barn door with authentic herringbone chevron pattern for farmhouse charm.',
    price: 749.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_192861_Heritage_Herringbone_Chevron_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '19',
    name: 'Heritage Rustic Plank Barn Door',
    description: 'Authentic rustic plank design barn door for traditional farmhouse aesthetics.',
    price: 699.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '20',
    name: 'Heritage Salinas Z-Design Barn Door',
    description: 'Distinctive Z-pattern barn door with rustic Heritage styling for unique character.',
    price: 739.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_176737_Heritage_Salinas_Z_Design.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '20',
    name: 'Heritage Shaker Barn Door',
    description: 'Clean Shaker-style barn door with traditional craftsmanship and modern functionality.',
    price: 729.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '21',
    name: 'Heritage Sierra K-Design Barn Door',
    description: 'Rustic Sierra barn door with distinctive K-pattern design for authentic farmhouse appeal.',
    price: 739.00,
    category: 'Barn Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Premium sliding track hardware' },
        { label: 'Sizes', value: '30", 32", 36", 42" widths, custom heights' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '22',
    name: 'Melody LED Mirror 32x24',
    description: 'Rectangular LED-lit mirror for contemporary bathroom design with integrated lighting.',
    price: 249.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '23',
    name: 'Parsons Flush Panel Bifold Door',
    description: 'Minimalist flush panel bifold door perfect for contemporary and modern interiors.',
    price: 399.00,
    category: 'Bifold Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Heavy-duty pivot hinges' },
        { label: 'Sizes', value: '24", 30", 32", 36" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '24',
    name: 'Parsons Flush Panel Bypass Door',
    description: 'Clean, minimalist flush panel design perfect for modern and contemporary interiors.',
    price: 489.00,
    category: 'Bypass Doors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Mechanism', value: 'Smooth-glide track system' },
        { label: 'Sizes', value: '48", 60", 72", 80", 96" widths available' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '25',
    name: 'Provincial 8-Lite Pivot Door',
    description: 'Elegant pivot door with eight glass panels for sophisticated closet entrance solutions.',
    price: 599.00,
    category: 'Pivot Doors',
    image: '/images/arcat/renin_205720_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
  {
    id: '26',
    name: 'Rectangle Flush Pull Handle',
    description: 'Black rectangular flush-mount door pull with recessed design for contemporary styling.',
    price: 59.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '27',
    name: 'Round Flush Pull Handle',
    description: 'Stainless steel round flush-mount door pull with brushed finish for modern aesthetics.',
    price: 49.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '28',
    name: 'Spectrum Bypass Bracket Kit',
    description: 'Professional bypass barn door bracket system for dual door installations.',
    price: 349.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '29',
    name: 'Spectrum Soft Close Kit',
    description: 'Advanced soft-close mechanism for smooth, quiet barn door operation with premium feel.',
    price: 159.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '30',
    name: 'Spectrum Track Hardware Kit',
    description: 'Premium barn door track hardware system with smooth operation and durable construction.',
    price: 299.00,
    category: 'Hardware',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Stainless steel construction' },
        { label: 'Finish', value: 'Multiple finish options available' },
        { label: 'Warranty', value: 'Lifetime mechanical warranty' },
    ],
  },
  {
    id: '31',
    name: 'Symphony LED Mirror 32x24',
    description: 'Premium rectangular LED-lit mirror with modern styling for luxury bathroom applications.',
    price: 279.00,
    category: 'Mirrors',
    image: '/images/arcat/renin_199064_hd.jpg',
    specs: [
        { label: 'Material', value: 'Premium engineered wood core' },
        { label: 'Finish', value: 'Durable laminate surface' },
        { label: 'Warranty', value: '5-year manufacturer warranty' },
    ],
  },
];
